<template>
  <div v-if="loading" class="middle-centered">
    <div class="pulsate-fwd font-weight-bold text-tertiary-1 h2">
      <narwhal :size="`5em`" :color="`#e00033`" />
      Loading...
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      loading: false
    }
  },
  methods: {
    start() {
      this.loading = true
    },
    finish() {
      this.loading = false
    }
  }
}
</script>

<style>
.middle-centered {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 9999;
}
.pulsate-fwd {
  animation: pulsate-fwd 0.5s ease-in-out infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-11-9 11:21:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
@keyframes pulsate-fwd {
  0% {
    transform: scale(1);
  }
  50% {
    transform: scale(1.1);
  }
  100% {
    transform: scale(1);
  }
}

</style>
