apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-deployment"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "{{  .Chart.Name }}-selector"
      version: "current"
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
        version: "current"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: "pub-sub"
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.servicePort}}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: GCP_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: project-dashboard
                key: GCP_PROJECT_ID
          - name: LINK_DISCOVERER_URL
            # value: "https://link-discoverer-enwgt7akpq-uw.a.run.app/discover"
            value: "https://link-discover-unauth-enwgt7akpq-uc.a.run.app/discover"
          - name: GKE
            value: "true"
          - name : "EXCESSIVE_PAGE_LIMIT"
            value: "25"
          - name: BROWSER_URL
            value: "stratypus.tk"
          - name: DATABASE_MAX_CONNECTIONS
            value: "10"
          - name: DATABASE_MIN_CONNECTIONS
            value: "0"
          - name: DATABASE_IDLE
            value: "1000"
          - name: DATABASE_AQUIRE
            value: "1000"
          - name: DATABASE_EVICT
            value: "1000"
          - name: DATABASE_SSL
            value: "true"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: project-dashboard
                key: DATABASE_URL
          - name: DATABASE_CA
            valueFrom:
              secretKeyRef:
                name: annotation
                key: DATABASE_CA
          - name: DATABASE_CERT
            valueFrom:
              secretKeyRef:
                name: annotation
                key: DATABASE_CERT
          - name: DATABASE_KEY
            valueFrom:
              secretKeyRef:
                name: annotation
                key: DATABASE_KEY
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: crs
                key: REDIS_URL
          - name: ASSET_SCRAPER_URL
            valueFrom:
              secretKeyRef:
                name: project-dashboard
                key: ASSET_SCRAPER_URL
          - name: PORT
            value : "{{ .Values.service.servicePort }}"
        {{- if .Values.image.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.image.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.image.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.image.readinessProbe | indent 10 }}
        {{- end }}